// <auto-generated />
using System;
using MSI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MIS.DataAccess.Migrations
{
    [DbContext(typeof(PoliceContext))]
    [Migration("20210423081915_final-migration")]
    partial class finalmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MIS.Model.CriminalRecordPoliceman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CriminalRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateWhenWasAdded")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PolicemanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CriminalRecordId");

                    b.HasIndex("PolicemanId");

                    b.ToTable("CriminalRecordPolicemen");
                });

            modelBuilder.Entity("MIS.Model.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CriminalRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriminalRecordId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MIS.Model.MeetingPoliceman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicemanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PolicemanId");

                    b.ToTable("MeetingPolicemen");
                });

            modelBuilder.Entity("MIS.Model.MeetingRequestPoliceman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MeetingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicemanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRequestId");

                    b.HasIndex("PolicemanId");

                    b.ToTable("MeetingRequestPolicemen");
                });

            modelBuilder.Entity("MSI.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MSI.Model.CriminalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedById");

                    b.ToTable("CriminalRecords");
                });

            modelBuilder.Entity("MSI.Model.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MSI.Model.MeetingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.ToTable("MeetingRequests");
                });

            modelBuilder.Entity("MSI.Model.PoliceSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RootPolicemanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("RootPolicemanId");

                    b.ToTable("PoliceSections");
                });

            modelBuilder.Entity("MSI.Model.Policeman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PoliceSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicemanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliceSectionId");

                    b.HasIndex("PolicemanId");

                    b.ToTable("Policemen");
                });

            modelBuilder.Entity("MSI.Model.PolicemanMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicemanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PolicemanId");

                    b.ToTable("PolicemanMeetings");
                });

            modelBuilder.Entity("MIS.Model.CriminalRecordPoliceman", b =>
                {
                    b.HasOne("MSI.Model.CriminalRecord", "CriminalRecord")
                        .WithMany()
                        .HasForeignKey("CriminalRecordId");

                    b.HasOne("MSI.Model.Policeman", "Policeman")
                        .WithMany()
                        .HasForeignKey("PolicemanId");

                    b.Navigation("CriminalRecord");

                    b.Navigation("Policeman");
                });

            modelBuilder.Entity("MIS.Model.Document", b =>
                {
                    b.HasOne("MSI.Model.CriminalRecord", null)
                        .WithMany("Documents")
                        .HasForeignKey("CriminalRecordId");
                });

            modelBuilder.Entity("MIS.Model.MeetingPoliceman", b =>
                {
                    b.HasOne("MSI.Model.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.HasOne("MSI.Model.Policeman", "Policeman")
                        .WithMany()
                        .HasForeignKey("PolicemanId");

                    b.Navigation("Meeting");

                    b.Navigation("Policeman");
                });

            modelBuilder.Entity("MIS.Model.MeetingRequestPoliceman", b =>
                {
                    b.HasOne("MSI.Model.MeetingRequest", "MeetingRequest")
                        .WithMany()
                        .HasForeignKey("MeetingRequestId");

                    b.HasOne("MSI.Model.Policeman", "Policeman")
                        .WithMany()
                        .HasForeignKey("PolicemanId");

                    b.Navigation("MeetingRequest");

                    b.Navigation("Policeman");
                });

            modelBuilder.Entity("MSI.Model.CriminalRecord", b =>
                {
                    b.HasOne("MSI.Model.Policeman", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("MSI.Model.MeetingRequest", b =>
                {
                    b.HasOne("MSI.Model.Policeman", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("MSI.Model.PoliceSection", b =>
                {
                    b.HasOne("MSI.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("MSI.Model.Policeman", "RootPoliceman")
                        .WithMany()
                        .HasForeignKey("RootPolicemanId");

                    b.Navigation("Address");

                    b.Navigation("RootPoliceman");
                });

            modelBuilder.Entity("MSI.Model.Policeman", b =>
                {
                    b.HasOne("MSI.Model.PoliceSection", null)
                        .WithMany("Policemen")
                        .HasForeignKey("PoliceSectionId");

                    b.HasOne("MSI.Model.Policeman", null)
                        .WithMany("Subordinates")
                        .HasForeignKey("PolicemanId");
                });

            modelBuilder.Entity("MSI.Model.PolicemanMeeting", b =>
                {
                    b.HasOne("MSI.Model.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.HasOne("MSI.Model.Policeman", "Policeman")
                        .WithMany()
                        .HasForeignKey("PolicemanId");

                    b.Navigation("Meeting");

                    b.Navigation("Policeman");
                });

            modelBuilder.Entity("MSI.Model.CriminalRecord", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MSI.Model.PoliceSection", b =>
                {
                    b.Navigation("Policemen");
                });

            modelBuilder.Entity("MSI.Model.Policeman", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
